chore(deps): add missing typescript dev dependency (#458)
* chore(deps): add missing typescript dev dep

Fixes error during tests:

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

Error: Spawning typechecker failed - is typescript installed?
Caused by: Error: spawn tsc ENOENT

* chore(husky): switch to pnpx as it is the project's package manager